# Generated by Django 5.2.3 on 2025-07-08 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date du rendez-vous')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('objet', models.CharField(help_text='Ex: Gestion du stress, Confiance en soi...', max_length=200, verbose_name='Objet de la séance')),
                ('duree', models.IntegerField(choices=[(60, '1 heure'), (90, '1h30'), (120, '2 heures')], default=60, verbose_name='Durée')),
                ('notes_coach', models.TextField(blank=True, help_text='Notes privées, non visibles par le client', null=True, verbose_name='Notes du coach')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Séance',
                'verbose_name_plural': 'Séances',
                'ordering': ['date', 'heure_debut'],
                'unique_together': {('client', 'date', 'heure_debut')},
            },
        ),
    ]
